"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EIP712__factory = exports.ECDSA__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ECDSA__factory_1 = require("./ECDSA__factory");
Object.defineProperty(exports, "ECDSA__factory", { enumerable: true, get: function () { return ECDSA__factory_1.ECDSA__factory; } });
var EIP712__factory_1 = require("./EIP712__factory");
Object.defineProperty(exports, "EIP712__factory", { enumerable: true, get: function () { return EIP712__factory_1.EIP712__factory; } });
//# sourceMappingURL=index.js.map