/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IVesting {
  export type VestingScheduleStruct = {
    from: AddressLike;
    start: BigNumberish;
    token: AddressLike;
    totalAmount: BigNumberish;
    amountReleased: BigNumberish;
    nextReleaseStep: BigNumberish;
  };

  export type VestingScheduleStructOutput = [
    from: string,
    start: bigint,
    token: string,
    totalAmount: bigint,
    amountReleased: bigint,
    nextReleaseStep: bigint
  ] & {
    from: string;
    start: bigint;
    token: string;
    totalAmount: bigint;
    amountReleased: bigint;
    nextReleaseStep: bigint;
  };

  export type VestingInfoStruct = {
    schedule: IVesting.VestingScheduleStruct;
    release: IAtomicSwapBase.ReleaseStruct[];
    beneficiary: AddressLike;
    orderId: BytesLike;
  };

  export type VestingInfoStructOutput = [
    schedule: IVesting.VestingScheduleStructOutput,
    release: IAtomicSwapBase.ReleaseStructOutput[],
    beneficiary: string,
    orderId: string
  ] & {
    schedule: IVesting.VestingScheduleStructOutput;
    release: IAtomicSwapBase.ReleaseStructOutput[];
    beneficiary: string;
    orderId: string;
  };
}

export declare namespace IAtomicSwapBase {
  export type ReleaseStruct = {
    durationInHours: BigNumberish;
    percentage: BigNumberish;
  };

  export type ReleaseStructOutput = [
    durationInHours: bigint,
    percentage: bigint
  ] & { durationInHours: bigint; percentage: bigint };
}

export interface IVestingInterface extends Interface {
  getFunction(nameOrSignature: "startVesting"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewVesting" | "Received" | "Released"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "startVesting",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      IAtomicSwapBase.ReleaseStruct[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "startVesting",
    data: BytesLike
  ): Result;
}

export namespace NewVestingEvent {
  export type InputTuple = [vesting: IVesting.VestingInfoStruct];
  export type OutputTuple = [vesting: IVesting.VestingInfoStructOutput];
  export interface OutputObject {
    vesting: IVesting.VestingInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVesting extends BaseContract {
  connect(runner?: ContractRunner | null): IVesting;
  waitForDeployment(): Promise<this>;

  interface: IVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  startVesting: TypedContractMethod<
    [
      orderId: BytesLike,
      buyer: AddressLike,
      token: AddressLike,
      totalAmount: BigNumberish,
      releases: IAtomicSwapBase.ReleaseStruct[]
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "startVesting"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      buyer: AddressLike,
      token: AddressLike,
      totalAmount: BigNumberish,
      releases: IAtomicSwapBase.ReleaseStruct[]
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "NewVesting"
  ): TypedContractEvent<
    NewVestingEvent.InputTuple,
    NewVestingEvent.OutputTuple,
    NewVestingEvent.OutputObject
  >;
  getEvent(
    key: "Received"
  ): TypedContractEvent<
    ReceivedEvent.InputTuple,
    ReceivedEvent.OutputTuple,
    ReceivedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "NewVesting(tuple)": TypedContractEvent<
      NewVestingEvent.InputTuple,
      NewVestingEvent.OutputTuple,
      NewVestingEvent.OutputObject
    >;
    NewVesting: TypedContractEvent<
      NewVestingEvent.InputTuple,
      NewVestingEvent.OutputTuple,
      NewVestingEvent.OutputObject
    >;

    "Received(address,uint256)": TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;
    Received: TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;

    "Released(address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
