"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISideLzAppUpgradable__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint16",
                name: "_dstChainId",
                type: "uint16",
            },
            {
                internalType: "address payable",
                name: "sender",
                type: "address",
            },
            {
                internalType: "bytes",
                name: "_payload",
                type: "bytes",
            },
        ],
        name: "sendLzMsg",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
class ISideLzAppUpgradable__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.ISideLzAppUpgradable__factory = ISideLzAppUpgradable__factory;
ISideLzAppUpgradable__factory.abi = _abi;
//# sourceMappingURL=ISideLzAppUpgradable__factory.js.map