"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AtomicSwapMsgValidator__factory = exports.AtomicSwapHelper__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AtomicSwapHelper__factory_1 = require("./AtomicSwapHelper__factory");
Object.defineProperty(exports, "AtomicSwapHelper__factory", { enumerable: true, get: function () { return AtomicSwapHelper__factory_1.AtomicSwapHelper__factory; } });
var AtomicSwapMsgValidator__factory_1 = require("./AtomicSwapMsgValidator__factory");
Object.defineProperty(exports, "AtomicSwapMsgValidator__factory", { enumerable: true, get: function () { return AtomicSwapMsgValidator__factory_1.AtomicSwapMsgValidator__factory; } });
//# sourceMappingURL=index.js.map