"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Vault__factory = exports.IVault__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IVault__factory_1 = require("./IVault__factory");
Object.defineProperty(exports, "IVault__factory", { enumerable: true, get: function () { return IVault__factory_1.IVault__factory; } });
var Vault__factory_1 = require("./Vault__factory");
Object.defineProperty(exports, "Vault__factory", { enumerable: true, get: function () { return Vault__factory_1.Vault__factory; } });
//# sourceMappingURL=index.js.map