"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IAtomicSwap__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IAtomicSwap__factory_1 = require("./IAtomicSwap__factory");
Object.defineProperty(exports, "IAtomicSwap__factory", { enumerable: true, get: function () { return IAtomicSwap__factory_1.IAtomicSwap__factory; } });
//# sourceMappingURL=index.js.map