[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./"},
    { access = "write", path = "./"}
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
bera="${BERA_TESTNET_URL"



