"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VaultPermit__factory = exports.Vault__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Vault__factory_1 = require("./Vault__factory");
Object.defineProperty(exports, "Vault__factory", { enumerable: true, get: function () { return Vault__factory_1.Vault__factory; } });
var VaultPermit__factory_1 = require("./VaultPermit__factory");
Object.defineProperty(exports, "VaultPermit__factory", { enumerable: true, get: function () { return VaultPermit__factory_1.VaultPermit__factory; } });
//# sourceMappingURL=index.js.map