export * from "./typechain";
import * as constants from "./constants/constants";
export declare const Settings: {
    atomicSwapHelper_sepolia: string;
    inChainAtomicSwap_mumbai: string;
    mockUSDC_mumbai: string;
    mockUSDT_mumbai: string;
    inChainAtomicSwap_sepolia: string;
    mockUSDC_sepolia: string;
    mockUSDT_sepolia: string;
    atomicSwapMsgValidator_sepolia: string;
    interchainAtomicSwapLogic_sepolia: string;
    sideBridgeAddress_sepolia: string;
    interChainAtomicSwap_sepolia: string;
    atomicSwapHelper_bnb: string;
    atomicSwapMsgValidator_bnb: string;
    interchainAtomicSwapLogic_bnb: string;
    sideBridgeAddress_bnb: string;
    interChainAtomicSwap_bnb: string;
    vesting_sepolia: string;
    atomicSwapStateLogic_sepolia: string;
    tokenTransferHelper_sepolia: string;
    atomicSwapStateLogic_bnb: string;
    tokenTransferHelper_bnb: string;
    vesting_bnb: string;
    inChainAtomicSwap_bnb: string;
    mockUSDC_bnb: string;
    mockUSDT_bnb: string;
};
export declare const CONSTANTS: typeof constants;
