/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAtomicSwapBase } from "./IAtomicSwapBase";
export type { IOwnablePausable } from "./IOwnablePausable";
