"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IInchainAtomicSwap__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IInchainAtomicSwap__factory_1 = require("./IInchainAtomicSwap__factory");
Object.defineProperty(exports, "IInchainAtomicSwap__factory", { enumerable: true, get: function () { return IInchainAtomicSwap__factory_1.IInchainAtomicSwap__factory; } });
//# sourceMappingURL=index.js.map